### ISSUE TITLE
ExercisesCheatSheet.md and/or code/*/README.md

### ISSUE THREAD

**Issue by chavid** [hsf-training/cpluspluscourse#117]
@all 

On top of the global `ExercisesCheatSheet.md`, there are some `README.md` files in each subdirectory of `code`, which were meant to play the role of detailed instructions for the exercices, while  `ExercisesCheatSheet.md` was meant to give the global point of view, and especially the order of the exercices.

Has this changed, and `ExercisesCheatSheet.md` is now meant to contain anything ? If so, it would be better to remove the outdated README files. If not (my personal prefered option), we should make them up-to-date...

**Comment by chavid** [comment]
I see that we even have a third option : in `code/functions`, the expected tasks are given in the main program file. Some more consistency would help learners.

**Comment by chavid** [comment]
I apologize I did not retry the exercices before...

**Comment by hageboeck** [comment]
The initial idea was:
- Cheat sheet for mentors (it's OK if students have a look, though)
- Rest for students

I agree that one should unify `README` and in-file tasks, though.

**Comment by chavid** [comment]
> 



> The initial idea was:
> 
>     * Cheat sheet for mentors (it's OK if students have a look, though)
> 
>     * Rest for students
> 
> I agree that one should unify `README` and in-file tasks, though.

Understood. So, do we prefer the instructions in the README.md and/or in the cpp file ?
I have a slight preference for README.md, because of the slightly improved rendering of markdown, and the unique file name, while some examples may have several cpp files.
Yet I understand the benefit of having anything in a single cpp file.

**Comment by bernhardmgruber** [comment]
I agree with the better readability of the `README.md`, although I don't think we need rich formatting capabilities. I don't think GitHub is a big argument, since the `README.md` is pointless without having the code next to it. Students are also expected to change the code, so they need to check it out anyway. And I think it is generally better to view a single file instead of two side by side. Having instructions in the code also allows them to be interleaved with the code, like in my `operators` exercise, where every new task comes with a few more lines of code the students need to get working.

In any case, I would like to avoid to have a redundant `README.md` and documentation in the source files. I am fine with each exercise to choose differently. I am leaning towards 1.

**Comment by chavid** [comment]
Then the solution of stephan is best : the README.md just possibly reminds the basic building instructions, gives the name of the main program file, and let the students discover the tasks within this file.

**Comment by sponce** [comment]
I think the introduction of the different types of documentation were having different goals still applying today : 
  - cheat sheet is only for mentors, with solutions and key points to discuss, I do not think there is a debate there
  - readmes hosts indeed the "basic building instructions, gives the name of the main program file, and let the students discover the tasks". It's not detailed and should not content C++ code
  - inside the code, you get more precise help on what should/could be done and also where (when the code is long and only one part needs to be worked on)
So with that in mind, I do not think we should drop anything. Maybe just relocate things or drop duplicate info when it's not all in the right place.

**Comment by chavid** [comment]
Agreed.
