### ISSUE TITLE
East or west const ?

### ISSUE THREAD

**Issue by chavid** [hsf-training/cpluspluscourse#125]
A choice has been made and should be enforced everywhere ?

**Comment by bernhardmgruber** [comment]
I see a mixture of east/west const in the slides. There is also a mix of `int* a` and `int *a` in the slides. I personally don't care too much what's in the slides. I might even believe that the mix shows the students that there are multiple styles in use.

**Comment by chavid** [comment]
Ok.

**Comment by hageboeck** [comment]
We agreed during the 2nd or 3rd run of the course that "new stuff" should use `Type const &`, because Sébastien always teaches "const acts to the left, but there's one exception".
I think that's a good strategy, because it will help you deciphering cases like
`Type & *` with various consts on the way.

So what I would say: East const whenever you touch something, unless it's the slide that introduces west const.
