### ISSUE TITLE
Comments - 3rd HEP C++ Course

### ISSUE THREAD

**Issue by roiser** [hsf-training/cpluspluscourse#17]
I open this issue to collect all comments which cannot be done via PRs and were collected during the Aug HEP C++ Course.

- [x] function argument defaults are not mentioned yet. It may make sense to mention them during the first day in a slide.

**Comment by roiser** [comment]
Comment from today (Tuesday) training. We tell students to not use pointers and todays training is mostly using pointers. My answer, how to deal with pointers comes on Thursday and sometimes its unavoidable.

**Comment by hageboeck** [comment]
- [ ] Add clang-tidy to static source analysis?

**Comment by roiser** [comment]
constness 2nd slide (143) move the examples from pointer to refs (we said don't use pointers ...)

**Comment by hageboeck** [comment]
> constness 2nd slide (143) move the examples from pointer to refs (we said don't use pointers ...)

I thought about this, but references are per definition like "const pointers". So with references, there's only ever `type const &`.
It makes sense, though, to repeat constness with references.

**Comment by roiser** [comment]
145  put the  "const" after in the function  parameter

**Comment by roiser** [comment]
- [ ] on  "full power of noexcept" (slide  159) templates are used but only  come later  ... minor ...

**Comment by roiser** [comment]
slide "guaranteed copy   elision" (173) add destructor and  assignment operator

**Comment by bernhardmgruber** [comment]
Feedback for Wednesday:

- [ ] slide 256: we could mention vim (next to emacs) and CLion (paid, free student version)
- [ ] slide 261: needs update for modules (but I guess that can wait a bit until all compilers have it)
- [ ] slide 262: icc is deprecated now, will be replaced by icx (clang/LLVM based Intel compiler)
- [ ] slide: 264: are autotools portable (Windows)? I thought they rely on shell scripts
- [ ] exercise code: consider not using std::endl, if just a newline is needed and no flush
- [ ] slide 267: maybe add that IDEs offer very rich debugging experiences
- [ ] slide 271: asan is also supported by MSVC on Windows
- [ ] slide 274: compared to the previous tools, asan is explained by Stephan in quite some detail and on a very technical level. maybe a bit overwhelming. let's wait for student feedback
- [ ] slide 276: did we mention what a CI is?
- [ ] since we mention ASAN, should we mention TSAN and UBSAN? since we also mention helgrind
- [ ] since we mention callgrind, we should also mention perf (didn't Enrico mention this the other day?)
- [ ] slide 288: we need to mention clang-tidy
- [ ] during KCacheGrind exercise, compiler was smart enough to precompute sqrt(5): we could mention objdump or better godbolt.org as ways to look at the assembly
- [ ] slide 148: the constexpr has a single return statement because of C++11, but it would be really more readable to have an if statement and require C++14
- [ ] slide 150: requires C++14 (top right on slide)

**Comment by bernhardmgruber** [comment]
Feedback for Thursday (when I participated):

- [ ] slide 155ff: dynamic exception specification is not only deprecated, but now removed since C++20
- [ ] slide 158: replace "throw statement" by "dynamic exception specification", because throw statements are still fully allowed :)
- [ ] slide 159: maybe add an example assigning the result of noexcept to a variable, to stress that noexcept evaluates to a bool:
	constexpr bool callCannotThrow = noexcept(f());
	if constexpr (callCannotThrow) { ... }
	but Sebastian explained it well verbally
- [ ] slide 163: add result.reserve(n);, but otherwise this code is perfectly fine and will technically call the move ctor in "return result;", probably even apply NRVO (not guaranteed), we should not call this code inefficient
- [ ] slide 166: T c = T(2) will not move assign, but just call the constructor like: T c(2);
- [ ] slide 166: T d = func(), also show: T func() { ... }
- [ ] slide 168: prefer the swap method as a hidden friend :) you actually do it that way on slide 169
- [ ] slide 169: the constructor delegation also happens when we do not write Movable() on line 4
- [ ] slide 169: it could help to add:
	Movable a, b;
	a = b; // operator= copy b into argument "other"
	a = std::move(b); // operator= move b into argument "other"

Feedback for Thursday (later, offline):

- [ ] slide 185: typo hash_set
- [ ] slide 190: the iterator based for loop is an abomination, and the range-for version (slide 195) should be shown immediately after the iterator one, maybe even on the same slide
- [ ] slide 191: bind2nd was removed in C++17, consider replacing the example by a lambda version, or, since lambdas are introduced later, dropping it
- [ ] slide 194: maybe replace "template syntax is simply awful" by "template syntax adds complexity", the syntax is not that awful :) also maybe change to: "compilers spit out long error novels" and maybe strike the "However, this has improved a lot with C++11", compilers have become quite ok now with template error messages, they are still long, but that is part of their nature. and they don't get much better with concepts, you now just have a nested stacking of which constraints you violate :D
- [ ] slide 195: maybe use std::reduce instead of std::accumulate, it is faster in several cases
- [ ] slide 197: I guess you don't have the time for it, but optional/any/variant would really benefit from a short example. the wording on the slides is correct but the students likely won't understand what it's useful for.
- [ ] slide 199: my favorit structured binding example is iterating over a map: for (const auto& [key, value] : map) { ... }
- [ ] we could consider adding a slide on CTAD (constructor template argument deduction). that works really great with structured bindings and multiple return types in case you don't want to define a struct for the return type:
	auto f() { int a; double b; std::string c; ...; return std::tuple{a, b, c}; }
	auto [a, b, c] = func();
- [ ] it's useful to know what the compiler generates from a lambda function and there is a great website to look at that: https://cppinsights.io/lnk?code=I2luY2x1ZGUgPHZlY3Rvcj4KI2luY2x1ZGUgPGFsZ29yaXRobT4KCmludCBtYWluKCkKewogIHN0ZDo6dmVjdG9yPGludD4gdnsxLCAyLCAzfTsKICBpbnQgaW5jcmVtZW50ID0gNTsKICBzdGQ6OnRyYW5zZm9ybShiZWdpbih2KSwgZW5kKHYpLCBiZWdpbih2KSwKICAgIFtpbmNyZW1lbnRdKGludCB2YWx1ZSkgewogICAgICByZXR1cm4gdmFsdWUgKyBpbmNyZW1lbnQ7CiAgICB9KTsKfQ==&insightsOptions=cpp17&std=cpp17&rev=1.0
    it's not just handy for lambdas, you can also check what the compilers creates for e.g. range-for
- [ ] slide 214f: the examples are too much C for me, people should not be reminded again that malloc, free, strncpy, FILE, fopen, fputs, fclose, EOF exist. maybe we can find a C++ version that news an array for processing some numbers, the FILE example is actually good, because it shows that C++ can do better than C here. But I am afraid that students will remember these codes as something they can use. Like we show FILE* a couple of times but never std::ifstream, so what will students remember when they need to read a file?
- [ ] slide 222: also use RAII to manage resources other than memory, like files
- [ ] exercise lambdas: replace header <ext/numeric>

**Comment by roiser** [comment]
- [  ] multi-threading, explain that memory is shared (vice versa multi-processing)

**Comment by roiser** [comment]
python

- [ ] move cppyy crash course on two slides to avoid small fonts

**Comment by roiser** [comment]
expert c++

- [ ] did we mention template specialization somewhere?

**Comment by sponce** [comment]
Most comments have now been addressed in !64, the rest has been converted into individual issues (#65, #66, #67, #68, #69, #70, #71, #72)
