### ISSUE TITLE
Advanced course contents

### ISSUE THREAD

**Issue by hageboeck** [hsf-training/cpluspluscourse#245]
| Day | Contents |
|----|-----------|

**Comment by sponce** [comment]
So let's try to have a first go at the content of an advanced course, chapter by chapter.
I propose to not do a dedicated pdf so that in case we need to go back to more basic concepts than expected, we have the whole set of slides. We could however create a second outline slide dedicated to advanced course, so that we know what to cover by simply going back to it.

Language basics -> as a short intro, a test of what people know and a recap of C++11/14/17 new features
--
  - scopesnamespaces (only unnamed namespace)
  - classenum (only enum class + using)
  - references (1 slide)
  - control (only init statements for if and switch & range based loops)
  - inline
  - assert

Object orientation (OO)
--
  - typecasting
  - operators (insisting on non member and friends)
  - functors
  - adl

Core modern \cpp
--
  - constexpr (consteval and constinit)
  - exceptions (noexcept and alternatives)
  - move (with no intro on the problem)
  - copyelision
  - templates (quick recap and CTAD)
  - lambda (quick recap, this and generic lambdas)
  - morestl
  - ranges
  - raii
  - random
  - initialization

Expert \cpp
--
  - variadictemplate
  - perfectforwarding
  - sfinae
  - cpp20concepts
  - cpp20spaceship
  - modules
  - coroutines

Useful tools
--
  - formatting
  - webtools
  - sanitizers
  - profiling
  - doxygen

Concurrency
--
  - threadsasync
  - mutexes
  - atomic
  - condition

Concerning the timing and order : 
  - let's start the the basics and OO part as a recap
  - half of core modern C++ down to move would probably also fit the first day
  - rest of core modern + tools and concurrency on 2nd day
  - as much as we can from expert on last day, providing we may not cover everything there. I would do the first 2, then spaceship, sfinae and concepts and that's probably it.

To be tested live obviously

**Comment by hageboeck** [comment]
I think it's a good curriculum. The only complication is:
Once you finish a topic, you cannot go to the next slide, but you have to go back to the index. It's harder on the speaker.

Can we try to have this 2nd index slide by the next meeting? My (so far) unsuccessful attempts at creating an index of good practices makes me think that this will be more work than we might wish for.

**Comment by sponce** [comment]
For good practices, it should not be so difficult. Just follow the example here : https://tex.stackexchange.com/questions/564098/how-to-add-include-the-title-of-custom-new-list-of-on-the-toc

You basically create a new kind of list, here listing the good practices (maybe call it `\listgoodpractice` and associate a new command `\goodpractice` which adds to the list and another one `\listofgoodpractices` which displays the lit, using the `\tocfile` command form `tocloft` package.
Then you only have to call `\goodpractice` in the definition of your goodpractice block

For the light weight table of content, the same approach would lead to redefine `\chapter`, `\section` and so on to be able to define where each one should be included. We would then have to change basically all slides...
For a first go, I would just jump over slides, and I volunteer then to do it, that is to present the first day. The 2 other days (and I propose we do one each, if it's fine for you) should be easier to deal with

**Comment by bernhardmgruber** [comment]
> For a first go, I would just jump over slides, and I volunteer then to do it, that is to present the first day. The 2 other days (and I propose we do one each, if it's fine for you) should be easier to deal with

Fine for me! I would prefer the concurrency and expert stuff over tooling, if that is fine with @hageboeck.

Should we propose to extend the course by one more day so we can overflow the expert content to a 4th day? Or just omit it and promise that there will be a follow-up course?

**Comment by sponce** [comment]
I was under the impression that whatever does not fit can be a good target for short sessions of 1h in the future here and there. That would allow people more experienced but simply not having had time to study a new topic (e.g. modules) to participate more easily.

**Comment by sponce** [comment]
Things have now settled down, let's close this
