### ISSUE TITLE
Exercise code/move : seg fault...

### ISSUE THREAD

**Issue by chavid** [hsf-training/cpluspluscourse#313]
@sponce @bernhardmgruber @hageboeck If I make and run the exercise original code... I got a segmentation fault. I am not sure it is on purpose ?

**Comment by chavid** [comment]
I guess `std::uniform_int_distribution<std::size_t> d{0, len}` should be `std::uniform_int_distribution<std::size_t> d{0, len-1}`, cause the second number is included in the intervall.

**Comment by chavid** [comment]
I wonder why the problem was not detected by the CI...

**Comment by hageboeck** [comment]
Precisely! I just wanted to add a PR

**Comment by hageboeck** [comment]
> I wonder why the problem was not detected by the CI...

That's because we're using random numbers, and the random engine is implementation defined. On some machines / distros, this will create a problem, on some, the 10000 might never be hit.
Furthermore, you might be able to read just one element after the vector, and still get away without a crash. That's a nice index bug ...

**Comment by chavid** [comment]
Still about the original exercise code, I wonder why the loop is reinitialising each element with an empty `T()`, line 31 of `trymove.cpp`.

**Comment by hageboeck** [comment]
That's to ensure that the default constructor of type `T` gets invoked. That's a relic from a time when this ran all the way with a custom vector I guess. I'll remove that as well ...
