### ISSUE TITLE
Items from 6th and JLab C++ Course

### ISSUE THREAD

**Issue by hageboeck** [hsf-training/cpluspluscourse#428]
- [ ]  ~~Add a slide on integral promotion~~

**Comment by bernhardmgruber** [comment]
OO morning lecture:

- [ ]  77: hint: member function, needs more explanation
- [ ]  what is UML?
- [ ]  should we have a dedicated good practice on header/source separation?
- [ ]  81: what is a class/object? all examples so far use `struct`. maybe mention that a class is a struct, or that all structs are actually classes. if there is a slide, move it earlier
- [ ]  81: move `this` slide further back if possible
- [ ]  82: dedicated slide on overloading during the function chapter?
- [ ]   85: this slide can go to the front, so we can discuss `struct` vs. `class`
- [ ]  mention: access specifiers are purely compile time. they don't offer any protection in the sense of security
- [ ]  around 86: add best practice: private data members with setters/getters vs. public data members (checking invariants, API evolution, ...). we may want to mention aggregates here as well (we hit aggregates later again: we should really add a slide for the basic course)
- [ ]  88 -> 89: maybe highlight the change on slide 89. same for slide 90.
- [ ]  92: ctors: we can name ctor arguments the same as data members, and this is also common
- [ ]  92: discuss naming conventions for data members? `m_`, `f...`.=, etc.
- [ ]   93: we should have given a brief description of `new` and `delete` before here. there was also a question on the difference of `delete` and `delete[]`
- [ ]  93: what happens when we leak memory? is there ever a situation where it's fine to leak?
- [ ]  93: is there a difference between using the initialization list and assigning in the ctor body?
- [ ]  95: split of rule of zero (stephan did not mention it and it's maybe too early). we could mention it after RAII and smart pointers
- [ ]  96: complete private members here for clarity
- [ ]  99: move this default ctor slide more to the front of the slide deck
- [ ]  107: @hageboeck wants to extend the slides on `static` members, at least by an example. @sponce suggests to entirely move it to the advanced course. zoom questions: why can we write to the static data member if it's private? and what is the point of static? maybe add an example of a factory function.

**Comment by bernhardmgruber** [comment]
OO/tools morning lecture

- [ ]  116: maybe replace the exception part by assigning to a variable etc.
- [ ]  119: Q: what is a real/typical use case for virtual functions?
- [ ]  119: what happends if I put the virtual only in the derived class? (Bernhard: this is not a compile error, the derived shadows the base, and classes derived from derived will use virtual dispatch)
- [ ]  do we discuss Liskov substitution?
- [ ]  123: c++11
- [ ]  125: should we use a pure virtual destructor instead of a defaulted one?
- [ ]  126: overlap of text on the slide
- [ ]  should we move virtual inheritance to the advanced course?
- [ ]  216: don't use nano :)
- [ ]  218: should we mention git GUIs, like GitKraken, RabbitCVS, TortoiseGit etc.?
- [ ]  tools: move some tool slides to advanced? Makefiles, cmake details? nm, ldd?

**Comment by bernhardmgruber** [comment]
From JLab course:

- [ ] 119: what happens if I omit the the `&`? -> Discuss slicing. Maybe also add a memory layout here that shows that a reference points to the start of the polymorphic object

**Comment by pcanal** [comment]
> 137: can we list all the overloadable operators?

The original table comes from: https://en.cppreference.com/w/cpp/language/operators
and does include the full list;
```
any of the following operators:+ - * / % ^ & \| ~ ! = < > += -= *= /= %= ^= &= \|= << >> >>= <<= == != <= >= <=> (since C++20) && \|\| ++ -- , ->* -> ( ) [ ]
```

**Comment by pcanal** [comment]
- [ ] 138 To help with exercises with long error output (we are looking at you operator overload excercise), teaching the student to pipe the output of the compiler (to be able to immediately see the first error rather than the last) might be helpful. e.g. `make 2>&1 | more` (or less) for zsh and bash.
