### ISSUE TITLE
C++ 20 : add slides about concepts

### ISSUE THREAD

**Issue by sponce** [hsf-training/cpluspluscourse#52]

**Comment by bernhardmgruber** [comment]
Most stuff related to concepts are advanced or expert features. They probably should come after introducing templates.

The advanced part is probably using standard library concepts:
```c++
template <typename F>
void f(F value) requires std::floating_point<F> {...};
```
We could also mention the various notations:
```c++
template <std::floating_point F>
void f(F value) {...};
```
and
```c++
void f(std::floating_point auto value) {...}; // still a template!
```
One implication is now that we can write generic functions without the `template` prelude:
```c++
void f(auto value) {...} // still a template!
```
This also effects variable declarations with concepts, although I suspect this will be used rarely:
```c++
  std::floating_point auto value = myVector.back(); // make sure value is a float/double/long double
```

Authoring concepts yourself is definitely an expert topic and takes a deeper understanding of what concepts are supposed to be. If you want to bring one example, fine for me. But otherwise I would completely leave this out of the course.

**Comment by chavid** [comment]
@sponce How long do you want it ?

**Comment by sponce** [comment]
Whatever you think suits. I do no think we are really constraint, especially that we are talking of the expert course.

**Comment by chavid** [comment]
2sponce Where should it go ? A new concepts.tex within talk/expert ?

**Comment by sponce** [comment]
Or we dedicate a chapter to C++20 ? No let's keep it in expert for the moment. On top with the new granular structure, it's easy to move things around anyway

**Comment by chavid** [comment]
When ttryin gto commit, I am sid :+1: 
```
codespell................................................................Failed
- hook id: codespell
- exit code: 65
```
What should I do ?

**Comment by chavid** [comment]
Done.
