### ISSUE TITLE
Add a slide on visitor pattern with lambdas

### ISSUE THREAD

**Issue by sponce** [hsf-training/cpluspluscourse#87]
_Originally posted by @sponce in https://github.com/hsf-training/cpluspluscourse/pull/79#discussion_r771845566_

**Comment by bernhardmgruber** [comment]
So this is essentially the overload pattern:
```c++
template<typename... Ts>
struct Overload : Ts ... { 
    using Ts::operator()...;
};
template<typename... Ts>
Overload(Ts...) -> Overload<Ts...>;

int main(){
    std::variant<char, long, float, int, double, long long> v;
    auto overloadSet = Overload{
        [](char) { return "char"; },
        [](int) { return "int"; },
        [](unsigned int) { return "unsigned int"; },
        [](long int) { return "long int"; },
        [](long long int) { return "long long int"; },
        [](auto) { return "unknown type"; },
    };
    std::visit(overloadSet, v);
}
```
(excerpted from [here](https://www.modernescpp.com/index.php/visiting-a-std-variant-with-the-overload-pattern))

There is a lot of stuff going on here like variadic templates, variadic using declarations of member functions, deduction guides and aggregate initialization into base classes. I would still show it to beginners, because the code is short and the usage is easy. But understanding why this works requires more knowledge on the language rules.
